#!/bin/sh
set -e

[ -e /proc/mtd ] || exit 1

MTD_NAME=mtd${MDEV#mtdblock}
NAME=$(awk "/$MTD_NAME:/ { print \$4 }" /proc/mtd | cut -d\" -f2)

if [ -z "$ACTION" ] || [ "x$ACTION" = xadd ]; then
  ln -sf /dev/$MDEV /dev/mtdblock_$NAME
else
  rm -f /dev/mtdblock_$NAME
fi 
